### PR TITLE
1st-shot: code-review, backwards-compatibilies, etc

### PR DESCRIPTION
**Pull request by sebres**
* adjusted style (more similar to dark theme of ubiquity)
* CmdUtils extended with makeSearchCommand (backwards compatibility to previous Ubiquity version);
* code review and enhancements:
  - introduced fuzzy search for command, commands sorted by rank (weight) and alphanumeric inside weights;
  - extended with common default preview functionality (CmdUtils._searchCommandPreview, etc);
  example for custom search-preview see insertenhsearchstub in options.js (or click on "enhanced search" in command-editor);
  - usage of `this` allowed now by execution of preview (backwards compatibility);
  - many fixes on style/dom of the ubiquity window, switched to table-layout (more responsive resp. RWD-capable now);
* reset tab/selection by update active tab (chrome, etc.)
* fix sporadic error if CmdUtils.backgroundWindow.error not available

### Examples for makeSearchCommand (with extended direct-preview):
```js
CmdUtils.makeSearchCommand({
  name: ["dict-cc", "dict-en"],
  author: {name: "Serg G. Brester (sebres)"},
  url: "http://www.dict.cc/?s={QUERY}",
  prevAttrs: {zoom: 0.8, scroll: [165 /*x*/, 200 /*y*/]},
  icon: "http://www.dict.cc/img/favicons/favicon4.png",
  description: "Searches dict.cc"
});

CmdUtils.makeSearchCommand({
  name: ["qwant"],
  author: {name: "Serg G. Brester (sebres)"},
  url: "https://www.qwant.com/?q={QUERY}&t=all",
  prevAttrs: {zoom: 0.75, scroll: [100, 0/*180*/], anchor: ["c_13", "c_22"] /*try to jump hash-anchors*/},
  icon: "https://www.qwant.com/favicon-152.png?1503916917494",
  description: "Searches quant.com"
});

CmdUtils.makeSearchCommand({
  name: "whois",
  author: {name: "Serg G. Brester (sebres)"},
  url: "http://whois.domaintools.com/{QUERY}",
  preview: 'none',
  icon: "http://whois.domaintools.com/favicon.ico",
  description: "Whois domaintools"
});

```

### CODE REVIEW

**Comment by Svalorzen** [comment]
Wow, nice work. I'll give this a through review ASAP. In the meantime, about backwards compatibility, could you check issue #5 (which I've just opened)?

I wrote some thoughts that me and rostok were having about possibly introducing a command-line like syntax to Ubiquity, in order to make it more useable and allow commands to interact with each other. This would probably mean breaking backwards compatibility, but I very strongly believe that such an interface is needed in order for Ubiquity to be much more useful.

**Comment by sebres** [comment]
> I'll give this a through review ASAP

There's no hurry. :)

As regards the #5, this (or similar) functionality is already implemented in original Ubiquity. For example see there the command `translate` (which accepts arguments `from` and `to`).

> This would probably mean breaking backwards compatibility

I don't think so: one can extend the syntax as well as the commands-API almost 99% compatible (if all incompatible enhancements will get optional mimic, resp. should be explicit allowed/specified in each command).

As regards as allow commands to interact with each other: easiest way would be to introduce something like `CmdUtils.executeCommand`, `CmdUtils.pipeToCommand`, `CmdUtils.sendToCommand`, etc.
And extend default syntax parser (that should be anyway more complex as it is currently) to support such interaction. Thus if any command should allow piping (e. g. `calc` out- and `print` in-direction), it can be relative easy extended by some rules (like `calc 2*2 | print`) or/and with option in command preventing or allowing it explicitly.

Anyway if someone needs a full backwards compatibility, it could be easy disabled via some global option, like `CmdUtils.AllowPipe = false;`

**Comment by rostok** [comment]
Hi and thanks for the PR! 
Unfortunately I am getting an error when previewing. To reproduce open popup and enter for example 'code' int the command input. There's ubiquity notification and the following stack trace.

```
popup.js:97 TypeError: preview_func.bind is not a function
    at pfunc (popup.js:94)
    at CmdUtils.loadScripts (popup.js:105)
    at loadScripts (cmdutils.js:310)
    at Object.tempfunc [as success] (cmdutils.js:314)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at HTMLScriptElement.c (jquery-2.2.4.min.js:4)
    at HTMLScriptElement.dispatch (jquery-2.2.4.min.js:3)
    at HTMLScriptElement.r.handle (jquery-2.2.4.min.js:3)
```

I love the preview in the iframe! This is so much easier and faster than getting all that data via jQuery.

**Comment by sebres** [comment]
> Unfortunately I am getting an error when previewing ...

Something is very very strange there...
The preview of `code-search` (by `code`) is string at all, so it should never produce this call stack,
because never enters 'string' scope of this switch:
https://github.com/rostok/ubichr/blob/89a53888c3f125400a73776c4c8f2a40a7a289bc/popup.js#L76-L78

Additionally it is very sporadic. I've executed it under debug with conditional brackpoint.
But strange it as I got this case, I take a look at preview_func - it was a string!
And watch of `typeof preview_func === 'string'` says true!
But the entry point as well as the call stack show me the default scope inside switch:
https://github.com/rostok/ubichr/blob/89a53888c3f125400a73776c4c8f2a40a7a289bc/popup.js#L79

**Comment by sebres** [comment]
got it - was a missing var (so variable was global in closure).
```diff
-        preview_func = cmd_struct.preview;
+    var preview_func = cmd_struct.preview;
```
Fixed now in https://github.com/rostok/ubichr/pull/4/commits/62ddfbe66125e5d9d41b4321d104c36a4b35323f#diff-d8c11c63dfd474a75f05fbbdba0889f8R70

I told you, it should be more `strict`, where such global vars declaration are not allowed.

**Comment by rostok** [comment]
pulled it, however I have simplified the style to make it look more flat

**Pull request merged**
